// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/rcppmlpackexamples_types.h"
#include <RcppArmadillo.h>
#include <RcppEnsmallen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// adaBoost
Rcpp::List adaBoost(const arma::mat dataset, const arma::vec labels, int iterations, double tolerance, int perceptronIter);
RcppExport SEXP _rcppmlpackexamples_adaBoost(SEXP datasetSEXP, SEXP labelsSEXP, SEXP iterationsSEXP, SEXP toleranceSEXP, SEXP perceptronIterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type dataset(datasetSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type perceptronIter(perceptronIterSEXP);
    rcpp_result_gen = Rcpp::wrap(adaBoost(dataset, labels, iterations, tolerance, perceptronIter));
    return rcpp_result_gen;
END_RCPP
}
// datasetExample
void datasetExample();
RcppExport SEXP _rcppmlpackexamples_datasetExample() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    datasetExample();
    return R_NilValue;
END_RCPP
}
// decisionTree
Rcpp::List decisionTree(const arma::mat dataset, const arma::ivec labels, double pct, int min_leaf_size, double minimum_gain_split, int maximum_depth);
RcppExport SEXP _rcppmlpackexamples_decisionTree(SEXP datasetSEXP, SEXP labelsSEXP, SEXP pctSEXP, SEXP min_leaf_sizeSEXP, SEXP minimum_gain_splitSEXP, SEXP maximum_depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type dataset(datasetSEXP);
    Rcpp::traits::input_parameter< const arma::ivec >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< double >::type pct(pctSEXP);
    Rcpp::traits::input_parameter< int >::type min_leaf_size(min_leaf_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type minimum_gain_split(minimum_gain_splitSEXP);
    Rcpp::traits::input_parameter< int >::type maximum_depth(maximum_depthSEXP);
    rcpp_result_gen = Rcpp::wrap(decisionTree(dataset, labels, pct, min_leaf_size, minimum_gain_split, maximum_depth));
    return rcpp_result_gen;
END_RCPP
}
// hoeffdingTrees
Rcpp::List hoeffdingTrees(const arma::mat dataset, const arma::vec labels, double pct, int nclasses);
RcppExport SEXP _rcppmlpackexamples_hoeffdingTrees(SEXP datasetSEXP, SEXP labelsSEXP, SEXP pctSEXP, SEXP nclassesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type dataset(datasetSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< double >::type pct(pctSEXP);
    Rcpp::traits::input_parameter< int >::type nclasses(nclassesSEXP);
    rcpp_result_gen = Rcpp::wrap(hoeffdingTrees(dataset, labels, pct, nclasses));
    return rcpp_result_gen;
END_RCPP
}
// kMeans
Rcpp::List kMeans(const arma::mat& data, const int& clusters);
RcppExport SEXP _rcppmlpackexamples_kMeans(SEXP dataSEXP, SEXP clustersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const int& >::type clusters(clustersSEXP);
    rcpp_result_gen = Rcpp::wrap(kMeans(data, clusters));
    return rcpp_result_gen;
END_RCPP
}
// linearRegression
arma::vec linearRegression(const arma::mat& matX, const arma::rowvec& vecY, const double lambda, const bool intercept);
RcppExport SEXP _rcppmlpackexamples_linearRegression(SEXP matXSEXP, SEXP vecYSEXP, SEXP lambdaSEXP, SEXP interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type matX(matXSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type vecY(vecYSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const bool >::type intercept(interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(linearRegression(matX, vecY, lambda, intercept));
    return rcpp_result_gen;
END_RCPP
}
// loanDefaultPrediction
Rcpp::List loanDefaultPrediction(arma::mat& loanDataFeatures, arma::vec& loanDataTargets, double pct);
RcppExport SEXP _rcppmlpackexamples_loanDefaultPrediction(SEXP loanDataFeaturesSEXP, SEXP loanDataTargetsSEXP, SEXP pctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type loanDataFeatures(loanDataFeaturesSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type loanDataTargets(loanDataTargetsSEXP);
    Rcpp::traits::input_parameter< double >::type pct(pctSEXP);
    rcpp_result_gen = Rcpp::wrap(loanDefaultPrediction(loanDataFeatures, loanDataTargets, pct));
    return rcpp_result_gen;
END_RCPP
}
// logisticRegression
Rcpp::List logisticRegression(const arma::mat& data, const arma::rowvec& labels, const double lambda);
RcppExport SEXP _rcppmlpackexamples_logisticRegression(SEXP dataSEXP, SEXP labelsSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(logisticRegression(data, labels, lambda));
    return rcpp_result_gen;
END_RCPP
}
// randomForest
Rcpp::List randomForest(const arma::mat dataset, const arma::vec labels, double pct, int nclasses, int ntrees);
RcppExport SEXP _rcppmlpackexamples_randomForest(SEXP datasetSEXP, SEXP labelsSEXP, SEXP pctSEXP, SEXP nclassesSEXP, SEXP ntreesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type dataset(datasetSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< double >::type pct(pctSEXP);
    Rcpp::traits::input_parameter< int >::type nclasses(nclassesSEXP);
    Rcpp::traits::input_parameter< int >::type ntrees(ntreesSEXP);
    rcpp_result_gen = Rcpp::wrap(randomForest(dataset, labels, pct, nclasses, ntrees));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rcppmlpackexamples_adaBoost", (DL_FUNC) &_rcppmlpackexamples_adaBoost, 5},
    {"_rcppmlpackexamples_datasetExample", (DL_FUNC) &_rcppmlpackexamples_datasetExample, 0},
    {"_rcppmlpackexamples_decisionTree", (DL_FUNC) &_rcppmlpackexamples_decisionTree, 6},
    {"_rcppmlpackexamples_hoeffdingTrees", (DL_FUNC) &_rcppmlpackexamples_hoeffdingTrees, 4},
    {"_rcppmlpackexamples_kMeans", (DL_FUNC) &_rcppmlpackexamples_kMeans, 2},
    {"_rcppmlpackexamples_linearRegression", (DL_FUNC) &_rcppmlpackexamples_linearRegression, 4},
    {"_rcppmlpackexamples_loanDefaultPrediction", (DL_FUNC) &_rcppmlpackexamples_loanDefaultPrediction, 3},
    {"_rcppmlpackexamples_logisticRegression", (DL_FUNC) &_rcppmlpackexamples_logisticRegression, 3},
    {"_rcppmlpackexamples_randomForest", (DL_FUNC) &_rcppmlpackexamples_randomForest, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_rcppmlpackexamples(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
